### ISSUE TITLE
Memory leak in IE. 

### ISSUE THREAD

**Issue by Kilowhisky** [jakerella/jquery-mockjax#272] opened 2015-11-24 20:57 UTC
I'm trying to track down memory issues in my application and i think i've stumbled upon a memory leak in mockjax where the request is still being held onto even though i never even invoked mockjax. 

![capture](https://cloud.githubusercontent.com/assets/7075666/11380350/4f3f99fe-92aa-11e5-9735-6fe8ca7eb98c.PNG)

I have created a very simple demo html file that shows the issue. 
[MockjaxMemoryLeak.txt](https://github.com/jakerella/jquery-mockjax/files/43202/MockjaxMemoryLeak.txt)

Steps to reproduce. 

1. Load the page in IE 11. 
2. Open the developer tools to the memory tab and start capturing.
3. After a few seconds take a snapshot. 
4. Wait until a few itterations pass and take another snapshot. 
5. Wait a minute or so and take another snapshot.

**Comment by dcneiner** [comment] 2015-11-25 04:30
Hi @Kilowhisky! Thanks for the detailed issue details, however what you are seeing is not a bug or a memory leak. Mockjax is primarily a testing and development framework that isn't meant for use in a production environment. The unmockedAjaxCalls is a feature that would most often be used in tests (or figuring out why a request wasn't caught by Mockjax) that allows you to see which settings were passed to `$.ajax` that weren't handled by Mockjax. Calling `$.mockjax.clear()` will remove all mocked calls and reset those variables, freeing the memory.

**Comment by jakerella** [comment] 2015-11-25 20:01
Yep... @dcneiner is spot on. Feel free to submit a PR that allows for turning off the tracking of unmocked calls. I could see that being helpful for some folks. In any case, I'm going to close this issue for now.

**Closed by jakerella** 2015-11-25 20:01 UTC
