### ISSUE TITLE
only work with jquery2.1.0, not 2.20 and upper

### ISSUE THREAD

**Issue by dstang2000** [jakerella/jquery-mockjax#346] opened 2019-05-29 03:07 UTC
hope suppert jquery>2.20 and 3.00 and 3.7 etc

**Comment by ca0v** [comment] 2019-06-03 13:55
Has this been confirmed?  Is there an alternative for newer versions of jquery?

**Comment by PurpleMagick** [comment] 2019-06-18 12:22
@ca0v well, I can replicate that using version 1.6.2 of mockjax:

[jQuery 2.1.0](https://jsbin.com/lizurac/1/edit?html,js,console)
[jQuery 2.2.0](https://jsbin.com/liwotum/1/edit?html,js,console)

there is no CDN copy of newer versions of jQuery, so I'll have to download and try it on my machine. I'll update with the results.

**Comment by jakerella** [comment] 2019-06-18 13:51
Hi! Sorry for the silence... been heads down at work. I test on all minor branches of jQuery (except I need to add 3.4.1). I [download the library](https://github.com/jakerella/jquery-mockjax/tree/master/lib) and [run the tests](https://github.com/jakerella/jquery-mockjax/blob/master/CONTRIBUTING.md#run-the-tests) on [multiple browsers](https://github.com/jakerella/jquery-mockjax#browsers-tested) using browserstack.

Since you folks can't verify, and I see the tests passing, I'm gonna close this one.

@dstang2000 If you have a specific error occurring, please open a new issue with that error report and I can take a look.

**Closed by jakerella** 2019-06-18 13:51 UTC
