### ISSUE TITLE
Doesn't match URL subsequently when namespace is specified

### ISSUE THREAD

**Issue by pribilinskiy** [jakerella/jquery-mockjax#318] opened 2017-05-11 13:41 UTC
I need to match the following: `/foobar/search` but that fails when `namespace` is specified.

```
$.mockjaxSettings.namespace = '/foobar';

$.mockjax({
	url: "/search",
});

$.getJSON('/foobar/search'); // works
$.getJSON('/foobar/search'); // throws error
})();
```

Works fine when `namespace` is not specified, when specifying it directly in the url, e.g. `url: /foobar/search`

Screenshot from Chrome DevTools:

![image](https://cloud.githubusercontent.com/assets/3078595/25952077/4887eb3a-3668-11e7-9ef6-0d5f605268ea.png)

**Comment by jakerella** [comment] 2017-05-11 13:43
I think this is a duplicate of #312. I need to tackle that one... :/ Sorry for the delay!

If you think this is not a duplicate let me know.

**Closed by jakerella** 2017-05-11 13:43 UTC
